server:
  port: 8888
spring:
  application:
    name: uncle-springboot
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
#        enable_lazy_load_no_trans: true
#        hbm2ddl:
#          auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dev_uncle?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456


